
server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/signup

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/login

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/health_check
          filters:
            - AuthorizationHeaderFilter


        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item/** # ??? ???
            - Method=POST, GET, PATCH
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/** # ??? ???
            - Method=POST, GET
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/** # ??? ???
            - Method=POST, GET, DELETE, PATCH
          filters:
            - RemoveRequestHeader=Cookie
            #- RewritePath=/user-service/(?<segment>.*), /$\{segment}


management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

token:
  expiration_time: 8600000
  secret: toyproject